# Generated by Django 4.1.3 on 2022-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_do_emprestimo', models.DecimalField(decimal_places=2, max_digits=10.2)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10.2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
