# Generated by Django 4.1.3 on 2022-11-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funds',
        ),
    ]
