# Generated by Django 4.1.3 on 2022-11-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='parcela',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='funds',
            name='total_parcelas',
            field=models.IntegerField(default=None),
        ),
    ]
