# Generated by Django 4.1.3 on 2022-11-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_delete_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valor_do_emprestimo',
            field=models.DecimalField(decimal_places=False, default=None, max_digits=10.2),
        ),
    ]
