# Generated by Django 4.1.3 on 2022-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_alter_funds_parcela_alter_funds_total_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='parcela',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='funds',
            name='total_parcelas',
            field=models.IntegerField(default=True),
        ),
    ]
