# Generated by Django 4.1.3 on 2022-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_funds_remove_user_list_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='data_de_emissao',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='funds',
            name='data_de_vencimento',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='funds',
            name='parcela',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='funds',
            name='preco_aquisicao',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10.2),
        ),
        migrations.AddField(
            model_name='funds',
            name='total_parcelas',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='uf',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
