# Generated by Django 4.1.3 on 2022-11-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0003_alter_user_valor_do_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valor_do_emprestimo',
            field=models.DecimalField(decimal_places=False, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=False, default=False, max_digits=10),
        ),
    ]
