# Generated by Django 4.1.3 on 2022-11-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0003_funds_data_de_emissao_funds_data_de_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='data_de_emissao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
