# Generated by Django 4.1.3 on 2022-11-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0004_alter_funds_valor_do_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=10, default=False, max_digits=10.2),
        ),
    ]
