# Generated by Django 4.1.3 on 2022-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0004_alter_user_valor_do_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parcela',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_parcelas',
            field=models.IntegerField(default=None),
        ),
    ]
