# Generated by Django 4.1.3 on 2022-11-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0005_alter_funds_valor_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='preco_aquisicao',
            field=models.DecimalField(decimal_places=10, default=False, max_digits=10.2),
        ),
    ]
