# Generated by Django 4.1.3 on 2022-11-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0005_alter_user_parcela_alter_user_total_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preco_aquisicao',
            field=models.DecimalField(decimal_places=False, default=False, max_digits=10),
        ),
    ]
