# Generated by Django 4.1.3 on 2022-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0005_alter_funds_data_de_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='data_de_vencimento',
            field=models.DateField(verbose_name='created_at'),
        ),
    ]
