# Generated by Django 4.1.3 on 2022-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0006_alter_funds_data_de_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='data_de_emissao',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='funds',
            name='data_de_vencimento',
            field=models.DateField(default=None),
        ),
    ]
