# Generated by Django 4.1.3 on 2022-11-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0007_alter_funds_data_de_emissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funds',
            name='data_de_emissao',
        ),
        migrations.AddField(
            model_name='funds',
            name='created_at',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='funds',
            name='data_de_vencimento',
            field=models.DateTimeField(default=None),
        ),
    ]
